name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Check version bump
        run: |
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:package.json | jq -r .version)
          PR_VERSION=$(jq -r .version package.json)
          if [ "$MAIN_VERSION" = "$PR_VERSION" ]; then
            echo "Error: Version must be bumped in package.json"
            exit 1
          fi

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Run ESLint
        run: pnpm run lint

      - name: Type check
        run: pnpm run ts:check
